# Generated by Django 5.1.7 on 2025-03-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('type_categorie', models.IntegerField(choices=[(0, 'Type 0'), (1, 'Type 1')])),
                ('descriptions', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Departements',
            fields=[
                ('deptno', models.AutoField(primary_key=True, serialize=False)),
                ('name_dept', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('empno', models.AutoField(primary_key=True, serialize=False)),
                ('name_emp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Employes',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('deptno', models.AutoField(primary_key=True, serialize=False)),
                ('executer', models.BooleanField()),
                ('writer', models.BooleanField()),
                ('reader', models.BooleanField()),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Previsions',
            fields=[
                ('id_prevision', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('date_operation', models.DateField()),
                ('montant', models.FloatField()),
                ('id_category', models.ForeignKey(db_column='idCategory', on_delete=django.db.models.deletion.CASCADE, to='budgetapp.categories')),
            ],
            options={
                'db_table': 'Previsions',
            },
        ),
        migrations.CreateModel(
            name='Realisations',
            fields=[
                ('id_realisation', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('date_operation', models.DateField()),
                ('montant', models.FloatField()),
                ('id_category', models.ForeignKey(db_column='idCategory', on_delete=django.db.models.deletion.CASCADE, to='budgetapp.categories')),
            ],
            options={
                'db_table': 'Realisations',
            },
        ),
        migrations.CreateModel(
            name='SoldeDebut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anne', models.IntegerField()),
                ('montant', models.FloatField()),
                ('id_departement', models.ForeignKey(db_column='idDepartement', on_delete=django.db.models.deletion.CASCADE, to='budgetapp.departements')),
            ],
            options={
                'db_table': 'soldeDebut',
            },
        ),
    ]
