# Generated by Django 5.1.7 on 2025-03-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employes',
            name='deptno',
            field=models.ForeignKey(db_column='deptno', default=1, on_delete=django.db.models.deletion.CASCADE, to='budgetapp.departements'),
        ),
    ]
