# Generated by Django 5.2 on 2025-04-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_categorieclient_categorieproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetteCRM',
            fields=[
                ('idRecette', models.AutoField(primary_key=True, serialize=False)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'recette_crm',
            },
        ),
    ]
