# Generated by Django 5.1.7 on 2025-03-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0002_employes_deptno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='executer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='writer',
            field=models.BooleanField(default=False),
        ),
    ]
