# Generated by Django 5.2 on 2025-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0003_recettecrm'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm',
            name='descComportement',
            field=models.CharField(default='Comportement', max_length=100),
        ),
    ]
