# Generated by Django 5.1.7 on 2025-03-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0003_alter_roles_executer_alter_roles_reader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previsions',
            name='deptno',
            field=models.ForeignKey(db_column='deptno', default=1, on_delete=django.db.models.deletion.CASCADE, to='budgetapp.departements'),
        ),
        migrations.AddField(
            model_name='previsions',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realisations',
            name='deptno',
            field=models.ForeignKey(db_column='deptno', default=1, on_delete=django.db.models.deletion.CASCADE, to='budgetapp.departements'),
        ),
        migrations.AddField(
            model_name='realisations',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
    ]
