# Generated by Django 5.2 on 2025-06-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0004_crm_desccomportement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenoms', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatutTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField()),
                ('categorie_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.categorieticket')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.client')),
                ('priorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.priorite')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatutTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_statuts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.statutticket')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAffectationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_attributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to='budgetapp.employes')),
                ('id_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgetapp.departements')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assignments', to='budgetapp.employes')),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.ticket')),
            ],
        ),
    ]
