# Generated by Django 5.2 on 2025-06-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0005_categorieticket_client_priorite_statutticket_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='motdepasse',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_utilisateur',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
